// Word lists for the game
const WORD_LISTS = {
  common: [
    "the", "and", "you", "that", "was", "for", "are", "with", "his", "they",
    "this", "have", "from", "not", "had", "can", "but", "what", "said", "each",
    "which", "she", "how", "their", "has", "two", "more", "her", "like", "time",
    "very", "when", "come", "here", "just", "than", "long", "back", "way", "much"
  ],
  
  tech: [
    "code", "debug", "pixel", "array", "function", "variable", "algorithm", "binary",
    "compile", "syntax", "framework", "database", "server", "client", "protocol",
    "encryption", "interface", "recursion", "iteration", "parameter", "callback",
    "asynchronous", "dependency", "repository", "deployment", "optimization"
  ],
  
  nature: [
    "forest", "ocean", "mountain", "river", "sunset", "rainbow", "thunder", "lightning",
    "butterfly", "eagle", "dolphin", "tiger", "coral", "crystal", "meadow", "canyon",
    "waterfall", "aurora", "glacier", "volcano", "breeze", "storm", "moonlight", "starlight"
  ],
  
  creative: [
    "imagination", "inspiration", "creativity", "artistry", "elegance", "harmony", 
    "symphony", "poetry", "painting", "sculpture", "dance", "melody", "rhythm",
    "texture", "gradient", "perspective", "composition", "balance", "contrast", "vivid"
  ],

  quotes: [
    "hello world", "good morning", "thank you", "see you later", "how are you",
    "nice to meet you", "have a great day", "take care", "good night", "well done",
    "keep going", "never give up", "dream big", "work hard", "stay focused",
    "believe in yourself", "make it happen", "think positive", "be kind", "stay strong",
    "live life", "chase dreams", "find happiness", "create magic", "build future",
    "learn grow", "adapt change", "overcome obstacles", "reach goals", "find balance",
    "embrace change", "trust process", "find purpose", "make difference", "spread joy"
  ]
};

// Font families for cyberpunk typography
const FONT_FAMILIES = [
  // Monospace fonts (primary for cyberpunk aesthetic)
  '"Courier New", monospace',
  'Monaco, monospace',
  '"Fira Code", monospace',
  '"Source Code Pro", monospace',
  '"JetBrains Mono", monospace',
  '"Cascadia Code", monospace',
  '"Hack", monospace',
  '"Inconsolata", monospace',
  '"Anonymous Pro", monospace',
  '"Space Mono", monospace',
  '"IBM Plex Mono", monospace',
  '"Roboto Mono", monospace',
  
  // Tech/Display fonts
  '"Impact", fantasy',
  '"Arial Black", sans-serif',
  '"Roboto Condensed", sans-serif',
  '"Bebas Neue", sans-serif',
  '"Oswald", sans-serif',
  '"Anton", sans-serif',
  '"Righteous", sans-serif',
  '"Fredoka One", sans-serif',
  '"Bangers", sans-serif',
  '"Permanent Marker", cursive',
  '"Rock Salt", cursive',
  '"Shadows Into Light", cursive',
  
  // Clean Sans-serif
  'Arial, sans-serif',
  'Helvetica, sans-serif',
  '"Roboto", sans-serif',
  '"Open Sans", sans-serif',
  '"Lato", sans-serif',
  '"Nunito", sans-serif',
  '"Poppins", sans-serif',
  '"Inter", sans-serif',
  '"Ubuntu", sans-serif',
  '"Noto Sans", sans-serif',
  '"Source Sans Pro", sans-serif',
  '"Work Sans", sans-serif',
  '"Montserrat", sans-serif',
  '"Raleway", sans-serif',
  
  // Bold display
  '"Orbitron", sans-serif',
  '"Exo 2", sans-serif',
  '"Rajdhani", sans-serif',
  '"Audiowide", sans-serif',
  '"Chakra Petch", sans-serif',
  '"Syncopate", sans-serif',
  '"Wallpoet", sans-serif',
  '"Russo One", sans-serif',
  '"Black Ops One", sans-serif',
  '"Press Start 2P", sansospace',
  '"VT323", monospace',
  '"Share Tech Mono", monospace',
  '"Audiowide", sans-serif',
  
  // Serif fonts
  'Georgia, serif',
  '"Times New Roman", serif',
  '"Playfair Display", serif',
  '"Merriweather", serif',
  '"Lora", serif',
  '"Crimson Text", serif',
  '"Libre Baskerville", serif',
  '"Source Serif Pro", serif',
  '"Noto Serif", serif',
  '"Bitter", serif',
  '"Spectral", serif',
  
  // Handwriting/Script fonts
  '"Dancing Script", cursive',
  '"Pacifico", cursive',
  '"Great Vibes", cursive',
  '"Satisfy", cursive',
  '"Kaushan Script", cursive',
  '"Allura", cursive',
  '"Alex Brush", cursive',
  '"Yellowtail", cursive',
  '"Tangerine", cursive',
  '"Sacramento", cursive',
  
  // Decorative/Display fonts
  '"Lobster", cursive',
  '"Bungee", sans-serif',
  '"Bungee Shade", sans-serif',
  '"Faster One", sans-serif',
  '"Fascinate", sans-serif',
  '"Fascinate Inline", sans-serif',
  '"Flavors", sans-serif',
  '"Fondamento", serif',
  '"Freckle Face", sans-serif',
  '"Frijole", sans-serif',
  '"Galada", cursive',
  '"Goblin One", sans-serif',
  '"Gorditas", sans-serif',
  '"Graduate", sans-serif',
  '"Grand Hotel", cursive',
  '"Gravitas One", sans-serif',
  '"Henny Penny", sans-serif',
  '"Holtwood One SC", serif',
  '"Homemade Apple", cursive',
  '"Iceberg", sans-serif',
  '"Iceland", sans-serif',
  '"Indie Flower", cursive',
  '"Irish Grover", sans-serif',
  '"Italianno", cursive',
  '"Jim Nightshade", cursive',
  '"Julee", cursive',
  '"Just Another Hand", cursive',
  '"Just Me Again Down Here", cursive',
  '"Kalam", cursive',
  '"Kaushan Script", cursive',
  '"Kavoon", sans-serif',
  '"Knewave", sans-serif',
  '"Kranky", sans-serif',
  '"Kreon", serif',
  '"Kristi", cursive',
  '"Kumar One", sans-serif',
  '"Kumar One Outline", sans-serif',
  '"Lakki Reddy", cursive',
  '"Lancelot", serif',
  '"Lato", sans-serif',
  '"League Script", cursive',
  '"Leckerli One", cursive',
  '"Ledger", serif',
  '"Lekton", sans-serif',
  '"Lemon", sans-serif',
  '"Libre Baskerville", serif',
  '"Life Savers", sans-serif',
  '"Lilita One", sans-serif',
  '"Limelight", sans-serif',
  '"Linden Hill", serif',
  '"Lobster", cursive',
  '"Lobster Two", sans-serif',
  '"Londrina Outline", sans-serif',
  '"Londrina Shadow", sans-serif',
  '"Londrina Sketch", sans-serif',
  '"Londrina Solid", sans-serif',
  '"Lora", serif',
  '"Love Ya Like A Sister", sans-serif',
  '"Loved by the King", cursive',
  '"Lovers Quarrel", cursive',
  '"Luckiest Guy", sans-serif',
  '"Lusitana", serif',
  '"Lustria", serif',
  '"Macondo", cursive',
  '"Macondo Swash Caps", cursive',
  '"Magra", sans-serif',
  '"Maiden Orange", sans-serif',
  '"Mako", sans-serif',
  '"Mallanna", sans-serif',
  '"Mandali", sans-serif',
  '"Marcellus", serif',
  '"Marcellus SC", serif',
  '"Marck Script", cursive',
  '"Margarine", sans-serif',
  '"Marko One", serif',
  '"Marmelad", sans-serif',
  '"Marvel", sans-serif',
  '"Mate", serif',
  '"Mate SC", serif',
  '"Maven Pro", sans-serif',
  '"McLaren", sans-serif',
  '"Meddon", cursive',
  '"MedievalSharp", cursive',
  '"Medula One", sans-serif',
  '"Megrim", sans-serif',
  '"Meie Script", cursive',
  '"Merienda", cursive',
  '"Merienda One", cursive',
  '"Merriweather", serif',
  '"Merriweather Sans", sans-serif',
  '"Metal", sans-serif',
  '"Metal Mania", sans-serif',
  '"Metamorphous", sans-serif',
  '"Metrophobic", sans-serif',
  '"Michroma", sans-serif',
  '"Milonga", sans-serif',
  '"Miltonian", sans-serif',
  '"Miltonian Tattoo", sans-serif',
  '"Miniver", sans-serif',
  '"Miss Fajardose", cursive',
  '"Modern Antiqua", sans-serif',
  '"Molengo", sans-serif',
  '"Molle", cursive',
  '"Monda", sans-serif',
  '"Monofett", sans-serif',
  '"Monoton", sans-serif',
  '"Monsieur La Doulaise", cursive',
  '"Montaga", serif',
  '"Montez", cursive',
  '"Montserrat", sans-serif',
  '"Montserrat Alternates", sans-serif',
  '"Montserrat Subrayada", sans-serif',
  '"Moul", sans-serif',
  '"Moulpali", sans-serif',
  '"Mountains of Christmas", cursive',
  '"Mouse Memoirs", sans-serif',
  '"Mr Bedfort", cursive',
  '"Mr Dafoe", cursive',
  '"Mr De Haviland", cursive',
  '"Mrs Saint Delafield", cursive',
  '"Mrs Sheppards", cursive',
  '"Muli", sans-serif',
  '"Mystery Quest", sans-serif',
  '"Neucha", sans-serif',
  '"Neuton", serif',
  '"New Rocker", sans-serif',
  '"News Cycle", sans-serif',
  '"Niconne", cursive',
  '"Nixie One", sans-serif',
  '"Nobile", sans-serif',
  '"Nokora", sans-serif',
  '"Norican", cursive',
  '"Nosifer", sans-serif',
  '"Nothing You Could Do", cursive',
  '"Noticia Text", serif',
  '"Noto Sans", sans-serif',
  '"Noto Serif", serif',
  '"Nova Cut", sans-serif',
  '"Nova Flat", sans-serif',
  '"Nova Mono", sansospace',
  '"Nova Oval", sans-serif',
  '"Nova Round", sans-serif',
  '"Nova Script", sans-serif',
  '"Nova Slim", sans-serif',
  '"Nova Square", sans-serif',
  '"Numans", sans-serif',
  '"Nunito", sans-serif',
  '"Odor Mean Chey", sans-serif',
  '"Offside", sans-serif',
  '"Old Standard TT", serif',
  '"Oldenburg", sans-serif',
  '"Oleo Script", sans-serif',
  '"Oleo Script Swash Caps", sans-serif',
  '"Open Sans", sans-serif',
  '"Open Sans Condensed", sans-serif',
  '"Oranienbaum", serif',
  '"Orbitron", sans-serif',
  '"Oregano", sans-serif',
  '"Orienta", sans-serif',
  '"Original Surfer", sans-serif',
  '"Oswald", sans-serif',
  '"Over the Rainbow", cursive',
  '"Overlock", sans-serif',
  '"Overlock SC", sans-serif',
  '"Ovo", serif',
  '"Oxygen", sans-serif',
  '"Oxygen Mono", sansospace',
  '"Pacifico", cursive',
  '"Paprika", sans-serif',
  '"Parisienne", cursive',
  '"Passero One", sans-serif',
  '"Passion One", sans-serif',
  '"Pathway Gothic One", sans-serif',
  '"Patrick Hand", cursive',
  '"Patrick Hand SC", sans-serif',
  '"Patua One", sans-serif',
  '"Paytone One", sans-serif',
  '"Peralta", sans-serif',
  '"Permanent Marker", cursive',
  '"Petit Formal Script", cursive',
  '"Petrona", serif',
  '"Philosopher", sans-serif',
  '"Piedra", sans-serif',
  '"Pinyon Script", cursive',
  '"Pirata One", sans-serif',
  '"Plaster", sans-serif',
  '"Play", sans-serif',
  '"Playball", cursive',
  '"Playfair Display", sans-serif',
  '"Playfair Display SC", sans-serif',
  '"Podkova", serif',
  '"Poiret One", sans-serif',
  '"Poller One", sans-serif',
  '"Poly", serif',
  '"Pompiere", sans-serif',
  '"Pontano Sans", sans-serif',
  '"Port Lligat Sans", sans-serif',
  '"Port Lligat Slab", serif',
  '"Pragati Narrow", sans-serif',
  '"Prata", serif',
  '"Preahvihear", sans-serif',
  '"Press Start 2P", sansospace',
  '"Princess Sofia", cursive',
  '"Prociono", serif',
  '"Prosto One", sans-serif',
  '"Puritan", sans-serif',
  '"Quando", serif',
  '"Quantico", sans-serif',
  '"Quattrocento", serif',
  '"Quattrocento Sans", sans-serif',
  '"Questrial", sans-serif',
  '"Quicksand", sans-serif',
  '"Quintessential", cursive',
  '"Qwigley", cursive',
  '"Racing Sans One", sans-serif',
  '"Radley", serif',
  '"Raleway", sans-serif',
  '"Raleway Dots", sans-serif',
  '"Rambla", sans-serif',
  '"Rammetto One", sans-serif',
  '"Ranchers", sans-serif',
  '"Rancho", cursive',
  '"Rationale", sans-serif',
  '"Redressed", cursive',
  '"Reenie Beanie", cursive',
  '"Revalia", sans-serif',
  '"Ribeye", sans-serif',
  '"Ribeye Marrow", sans-serif',
  '"Righteous", sans-serif',
  '"Risque", sans-serif',
  '"Roboto", sans-serif',
  '"Roboto Condensed", sans-serif',
  '"Roboto Slab", serif',
  '"Rochester", cursive',
  '"Rock Salt", cursive',
  '"Rokkitt", serif',
  '"Romanesco", cursive',
  '"Ropa Sans", sans-serif',
  '"Rosario", sans-serif',
  '"Rosarivo", serif',
  '"Rouge Script", cursive',
  '"Rozha One", serif',
  '"Rubik", sans-serif',
  '"Rubik Mono One", sans-serif',
  '"Rubik One", sans-serif',
  '"Ruda", sans-serif',
  '"Rufina", serif',
  '"Ruge Boogie", cursive',
  '"Ruluko", sans-serif',
  '"Rum Raisin", sans-serif',
  '"Ruslan Display", sans-serif',
  '"Russo One", sans-serif',
  '"Ruthie", cursive',
  '"Rye", sans-serif',
  '"Sacramento", cursive',
  '"Sail", sans-serif',
  '"Salsa", sans-serif',
  '"Sanchez", serif',
  '"Sancreek", sans-serif',
  '"Sansita One", sans-serif',
  '"Sarina", sans-serif',
  '"Satisfy", cursive',
  '"Scada", sans-serif',
  '"Schoolbell", cursive',
  '"Seaweed Script", sans-serif',
  '"Sevillana", cursive',
  '"Seymour One", sans-serif',
  '"Shadows Into Light", cursive',
  '"Shadows Into Light Two", cursive',
  '"Shanti", sans-serif',
  '"Share", sans-serif',
  '"Share Tech", sans-serif',
  '"Share Tech Mono", sansospace',
  '"Shojumaru", sans-serif',
  '"Short Stack", cursive',
  '"Siemreap", sans-serif',
  '"Sigmar One", sans-serif',
  '"Signika", sans-serif',
  '"Signika Negative", sans-serif',
  '"Simonetta", sans-serif',
  '"Sintony", sans-serif',
  '"Sirin Stencil", sans-serif',
  '"Six Caps", sans-serif',
  '"Skranji", sans-serif',
  '"Slabo 13px", serif',
  '"Slabo 27px", serif',
  '"Slackey", sans-serif',
  '"Smokum", sans-serif',
  '"Smythe", sans-serif',
  '"Sniglet", sans-serif',
  '"Snippet", sans-serif',
  '"Snowburst One", sans-serif',
  '"Sofadi One", sans-serif',
  '"Sofia", sans-serif',
  '"Sonsie One", sans-serif',
  '"Sorts Mill Goudy", serif',
  '"Source Code Pro", sansospace',
  '"Source Sans Pro", sans-serif',
  '"Source Serif Pro", serif',
  '"Special Elite", sans-serif',
  '"Spicy Rice", sans-serif',
  '"Spinnaker", sans-serif',
  '"Spirax", sans-serif',
  '"Squada One", sans-serif',
  '"Stalemate", cursive',
  '"Stalinist One", sans-serif',
  '"Stardos Stencil", sans-serif',
  '"Stint Ultra Condensed", sans-serif',
  '"Stint Ultra Expanded", sans-serif',
  '"Stoke", serif',
  '"Strait", sans-serif',
  '"Sue Ellen Francisco", cursive',
  '"Sunshiney", cursive',
  '"Supermercado One", sans-serif',
  '"Suwannaphum", sans-serif',
  '"Swanky and Moo Moo", cursive',
  '"Syncopate", sans-serif',
  '"Tangerine", cursive',
  '"Taprom", sans-serif',
  '"Tauri", sans-serif',
  '"Teko", sans-serif',
  '"Telex", sans-serif',
  '"Tenor Sans", sans-serif',
  '"Text Me One", sans-serif',
  '"The Girl Next Door", cursive',
  '"Tienne", serif',
  '"Tinos", serif',
  '"Titan One", sans-serif',
  '"Titillium Web", sans-serif',
  '"Trade Winds", sans-serif',
  '"Trocchi", serif',
  '"Trochut", sans-serif',
  '"Trykker", serif',
  '"Tulpen One", sans-serif',
  '"Ubuntu", sans-serif',
  '"Ubuntu Condensed", sans-serif',
  '"Ubuntu Mono", sansospace',
  '"Ultra", serif',
  '"Uncial Antiqua", sans-serif',
  '"Underdog", sans-serif',
  '"Unica One", sans-serif',
  '"UnifrakturCook", sans-serif',
  '"UnifrakturMaguntia", sans-serif',
  '"Unkempt", sans-serif',
  '"Unlock", sans-serif',
  '"Unna", serif',
  '"VT323", sansospace',
  '"Vampiro One", sans-serif',
  '"Varela", sans-serif',
  '"Varela Round", sans-serif',
  '"Vast Shadow", sans-serif',
  '"Vesper Libre", serif',
  '"Vibur", cursive',
  '"Vidaloka", serif',
  '"Viga", sans-serif',
  '"Voces", sans-serif',
  '"Volkhov", serif',
  '"Vollkorn", serif',
  '"Voltaire", sans-serif',
  '"Waiting for the Sunrise", cursive',
  '"Wallpoet", sans-serif',
  '"Walter Turncoat", cursive',
  '"Warnes", sans-serif',
  '"Wellfleet", sans-serif',
  '"Wendy One", sans-serif',
  '"Wire One", sans-serif',
  '"Yanone Kaffeesatz", sans-serif',
  '"Yellowtail", cursive',
  '"Yeseva One", sans-serif',
  '"Yesteryear", cursive',
  '"Zeyada", cursive'
];

// Get a random word from all categories
export function getRandomWord(): string {
  const allCategories = Object.values(WORD_LISTS);
  const allWords = allCategories.flat();
  return allWords[Math.floor(Math.random() * allWords.length)];
}

// Get a random word from a specific category
export function getRandomWordFromCategory(category: keyof typeof WORD_LISTS): string {
  const words = WORD_LISTS[category];
  return words[Math.floor(Math.random() * words.length)];
}

// Get a random font family
export function getFontFamily(): string {
  return FONT_FAMILIES[Math.floor(Math.random() * FONT_FAMILIES.length)];
}

// Get a font family based on word category (for themed styling)
export function getThemedFontFamily(category: keyof typeof WORD_LISTS): string {
  switch (category) {
    case 'tech':
      // Monospace fonts for tech words
      return ['"Courier New", monospace', 'Monaco, monospace', '"Fira Code", monospace'][
        Math.floor(Math.random() * 3)
      ];
    case 'creative':
      // Elegant serif fonts for creative words
      return ['Georgia, serif', '"Playfair Display", serif', '"Merriweather", serif'][
        Math.floor(Math.random() * 3)
      ];
    case 'nature':
      // Clean sans-serif fonts for nature words
      return ['"Open Sans", sans-serif', '"Roboto", sans-serif', '"Lato", sans-serif'][
        Math.floor(Math.random() * 3)
      ];
    case 'quotes':
      // Bold display fonts for quotes and phrases
      return ['"Orbitron", sans-serif', '"Exo 2", sans-serif', '"Rajdhani", sans-serif'][
        Math.floor(Math.random() * 3)
      ];
    default:
      return getFontFamily();
  }
}

export { WORD_LISTS, FONT_FAMILIES };
