const LONG_PHRASE_LIST = [
    // General interest longer phrases
    "plan a cross country road trip",
    "organize a surprise birthday party",
    "explore a new city on foot",
    "cook a delicious homemade meal",
    "read a captivating mystery novel",
    "visit a world famous landmark",
    "learn to play a musical instrument",
    "take a scenic train journey",
    "attend a live music concert",
    "volunteer at a local animal shelter",
    "host a family game night",
    "go stargazing in the countryside",
    "start a daily meditation practice",
    "write a letter to a friend",
    "bake fresh bread from scratch",
    "grow vegetables in your garden",
    "take a photography class online",
    "organize a community clean up",
    "watch a sunrise at the beach",
    "try a new sport or activity",
    
    // Nature/Outdoor longer phrases
    "hike through mountain trails",
    "swim in crystal clear waters",
    "climb to mountain summit",
    "explore dense forest paths",
    "camp under starry sky",
    "photograph wildlife in habitat",
    "raft down rushing river",
    "ski down snowy slopes",
    "dive into ocean depths",
    "climb ancient rock formations",
    "watch sunset over horizon",
    "explore hidden cave systems",
    "trek across vast desert",
    "sail across open waters",
    "climb towering waterfall",
    "explore coral reef ecosystem",
    "hike through misty valleys",
    "camp beside peaceful lake",
    "explore volcanic landscapes",
    "photograph aurora borealis",
    
    // Motivational/Inspirational longer phrases
    "pursue your dreams relentlessly",
    "overcome every obstacle gracefully",
    "believe in your inner strength",
    "transform challenges into opportunities",
    "embrace the journey of growth",
    "inspire others through your actions",
    "create positive change daily",
    "build meaningful relationships",
    "develop resilience through adversity",
    "cultivate inner peace daily",
    "spread kindness wherever possible",
    "achieve goals through persistence",
    "learn from every experience",
    "grow stronger through challenges",
    "make a difference in world",
    "follow your heart passionately",
    "trust the process completely",
    "celebrate small victories daily",
    "maintain hope during difficult times",
    "find beauty in simple moments",
    
    // Action/Adventure longer phrases
    "race against time pressure",
    "escape from dangerous situation",
    "navigate through complex maze",
    "survive in wilderness environment",
    "rescue trapped mountain climber",
    "explore ancient temple ruins",
    "solve mysterious puzzle box",
    "defeat powerful enemy boss",
    "complete challenging obstacle course",
    "discover hidden treasure chest",
    "scale treacherous cliff face",
    "cross raging river safely",
    "survive extreme weather conditions",
    "explore underwater shipwreck",
    "climb frozen waterfall",
    "navigate through dense jungle",
    "escape from burning building",
    "survive zombie apocalypse",
    "complete epic quest journey",
    "defeat dragon in battle",
    
    // Business/Professional longer phrases
    "develop comprehensive business strategy",
    "implement effective marketing campaign",
    "conduct thorough market research",
    "negotiate favorable contract terms",
    "optimize operational efficiency",
    "develop innovative product features",
    "establish strong brand identity",
    "build loyal customer relationships",
    "analyze competitive market landscape",
    "create compelling sales presentation",
    "manage complex project timeline",
    "resolve customer service issues",
    "develop strategic partnerships",
    "implement cost reduction measures",
    "conduct performance review meeting",
    "develop employee training program",
    "analyze financial performance metrics",
    "create detailed project proposal",
    "manage stakeholder expectations",
    "implement quality control measures",
    
    // Creative/Artistic longer phrases
    "paint beautiful landscape masterpiece",
    "compose original musical composition",
    "write compelling novel storyline",
    "sculpt intricate marble statue",
    "design innovative product concept",
    "create stunning photography portfolio",
    "choreograph dynamic dance routine",
    "direct compelling film narrative",
    "craft intricate jewelry design",
    "weave colorful textile pattern",
    "build detailed architectural model",
    "design immersive virtual reality",
    "create interactive art installation",
    "compose emotional piano melody",
    "paint vibrant abstract expression",
    "sculpt dynamic bronze figure",
    "write powerful poetry collection",
    "design elegant furniture piece",
    "create mesmerizing light show",
    "compose epic orchestral symphony",
    
    // Science/Discovery longer phrases
    "conduct groundbreaking research experiment",
    "analyze complex data patterns",
    "develop innovative scientific theory",
    "discover new species in rainforest",
    "explore distant planetary surface",
    "investigate mysterious phenomenon",
    "develop advanced medical treatment",
    "study ancient archaeological site",
    "analyze genetic mutation patterns",
    "explore deep ocean trenches",
    "conduct psychological behavior study",
    "develop renewable energy solution",
    "investigate paranormal activity",
    "study climate change patterns",
    "analyze astronomical observations",
    "develop artificial intelligence system",
    "conduct forensic crime investigation",
    "explore microscopic cellular structures",
    "study evolutionary adaptation patterns",
    "develop quantum computing algorithm",
    
    // Food/Culinary longer phrases
    "prepare gourmet five course meal",
    "bake elaborate wedding cake design",
    "grill perfectly seasoned steak",
    "create fusion cuisine masterpiece",
    "ferment traditional sourdough bread",
    "cure artisanal cheese varieties",
    "smoke barbecue ribs slowly",
    "prepare authentic ethnic dishes",
    "create molecular gastronomy dish",
    "bake delicate pastry creations",
    "brew craft beer from scratch",
    "cure and smoke salmon fillets",
    "prepare traditional holiday feast",
    "create chocolate truffle assortment",
    "ferment homemade kombucha tea",
    "prepare sushi master chef style",
    "bake artisan sourdough bread",
    "create elaborate dessert platter",
    "prepare slow cooked stew",
    "create charcuterie board spread"
];

export { LONG_PHRASE_LIST }; 