const PHRASE_LIST = [
    // Tech/Programming phrases
    "hello world",
    "git commit",
    "npm install",
    "sudo apt",
    "docker run",
    "ssh connect",
    "vim editor",
    "debug mode",
    "test suite",
    "api endpoint",
    "data base",
    "web server",
    "code review",
    "pull request",
    "merge conflict",
    "deploy app",
    "load balance",
    "cache hit",
    "time out",
    "error log",
    
    // Nature/Outdoor phrases
    "sun rise",
    "moon light",
    "ocean wave",
    "forest path",
    "mountain peak",
    "river flow",
    "bird song",
    "rain drop",
    "wind blow",
    "snow fall",
    "star light",
    "cloud drift",
    "flower bloom",
    "tree grow",
    "rock climb",
    "beach sand",
    "lake view",
    "cave deep",
    "storm cloud",
    "rain bow",
    
    // Motivational/Positive phrases
    "dream big",
    "work hard",
    "stay strong",
    "keep going",
    "never give up",
    "believe in yourself",
    "make it happen",
    "think positive",
    "be kind",
    "find happiness",
    "create magic",
    "build future",
    "learn grow",
    "adapt change",
    "overcome obstacles",
    "reach goals",
    "find balance",
    "embrace change",
    "trust process",
    "find purpose",
    
    // Action/Adventure phrases
    "run fast",
    "jump high",
    "climb wall",
    "swim deep",
    "fly away",
    "dance move",
    "fight back",
    "hide seek",
    "catch ball",
    "throw far",
    "kick goal",
    "hit target",
    "push through",
    "pull together",
    "lift heavy",
    "carry load",
    "break free",
    "escape room",
    "chase dream",
    "race time",
    
    // Food/Cooking phrases
    "cook meal",
    "bake cake",
    "grill meat",
    "fry egg",
    "boil water",
    "mix ingredients",
    "chop vegetables",
    "slice bread",
    "pour sauce",
    "stir pot",
    "taste test",
    "serve food",
    "eat healthy",
    "drink water",
    "fresh fruit",
    "hot soup",
    "cold ice",
    "sweet treat",
    "spicy food",
    "salty snack",
    
    // Business/Professional phrases
    "meet deadline",
    "send email",
    "call client",
    "make deal",
    "close sale",
    "plan strategy",
    "lead team",
    "give presentation",
    "write report",
    "review data",
    "analyze results",
    "create budget",
    "manage project",
    "solve problem",
    "improve process",
    "increase profit",
    "reduce cost",
    "expand market",
    "build brand",
    "gain market share",
    
    // Creative/Art phrases
    "paint picture",
    "draw sketch",
    "write story",
    "compose music",
    "design logo",
    "take photo",
    "edit video",
    "make sculpture",
    "weave fabric",
    "craft jewelry",
    "build model",
    "create art",
    "express emotion",
    "show talent",
    "share vision",
    "inspire others",
    "capture moment",
    "tell story",
    "share beauty",
    "spread joy",
    
    // Science/Discovery phrases
    "test hypothesis",
    "analyze sample",
    "record data",
    "measure results",
    "observe pattern",
    "study behavior",
    "examine evidence",
    "prove theory",
    "discover truth",
    "explore space",
    "research topic",
    "conduct experiment",
    "verify findings",
    "document process",
    "calculate formula",
    "solve equation",
    "predict outcome",
    "validate claim",
    "investigate mystery",
    "uncover secret"
];

export { PHRASE_LIST }; 